export const Data = [
  {
    id: "1",
    title: "Crypto Capital Preservation",
    drive: "https://drive.google.com/file/d/1ejfZDnrd6TpyuVMp68QYXkS9hY3oxIYy/view?usp=drive_link",
    link: "/Halaman/page/2/2/1",
    category: "Crypto Trading Principle",
  },
  {
    id: "2",
    title: "Hindari Terkena Drawdown Portfolio dalam",
    drive: "https://drive.google.com/file/d/1ilcsLA4ZKwqsrXc7rLNM53x0V65jtaPY/view?usp=drive_link",
    link: "/Halaman/page/2/2/2",
    category: "Crypto Trading Principle",
  },
  {
    id: "3",
    title: "Jangan Perna Trading Tanpa Stoploss",
    drive: "https://drive.google.com/file/d/1FFpo3_9YftvDd0j-qpHqcykIeJsSDpVp/view?usp=drive_link",
    link: "/Halaman/page/2/2/3",
    category: "Crypto Trading Principle",
  },
  {
    id: "4",
    title: "If It's Too Good To Be True, Then It Is To Good To Be True",
    drive: "https://drive.google.com/file/d/1u9td_rebu9RHGCg_7o1MD-N-u_qfFnnm/view?usp=drive_link",
    link: "/Halaman/page/2/2/4",
    category: "Crypto Trading Principle",
  },
  {
    id: "5",
    title: "Cara Main Setiap Market Beda",
    drive: "https://drive.google.com/file/d/1hkOp63zDDpg7yg0jMcp7y12QUxEvqCi4/view?usp=drive_link",
    link: "/Halaman/page/2/2/5",
    category: "Crypto Trading Principle",
  },
  {
    id: "6",
    title: "Seacrh For Market Confluence",
    drive: "https://drive.google.com/file/d/1n1LSR_DQtHH3IGDUHrDlNwWSiJeCTR6e/view?usp=drive_link",
    link: "/Halaman/page/2/2/6",
    category: "Crypto Trading Principle",
  },
  {
    id: "7",
    title: "Jangan Batesin Profit, Tapi Batesin Loss",
    drive: "https://drive.google.com/file/d/12mh6uWwiojYdR5uj5Nomj6sY7gF1reNi/view?usp=drive_link",
    link: "/Halaman/page/2/2/7",
    category: "Crypto Trading Principle",
  },
  {
    id: "8",
    title: "Anaylst Terbaik Adalah Diri Kalian Sendiri",
    drive: "https://drive.google.com/file/d/1_O5vmhPttn-DYjTNi3bP9XOWkuB1-Wee/view?usp=drive_link",
    link: "/Halaman/page/2/2/8",
    category: "Crypto Trading Principle",
  },
  {
    id: "9",
    title: "Exit Strategy 90% Dari Total Trade Kalian",
    drive: "https://drive.google.com/file/d/1CHdFmNF-1eB2BrzpKi3Zn40lvby2_EhW/view?usp=drive_link",
    link: "/Halaman/page/2/2/9",
    category: "Crypto Trading Principle",
  },
  {
    id: "10",
    title: "Trade Less When Winning",
    drive: "https://drive.google.com/file/d/1_79Hgyo0HRs_tdyedtnYzf_J2YoR1dhZ/view?usp=drive_link",
    link: "/Halaman/page/2/2/10",
    category: "Crypto Trading Principle",
  },
  {
    id: "11",
    title: "Selama ini Lu Salah Pake Trading Journal",
    drive: "https://drive.google.com/file/d/1bEEZcT0XRsCyN3a5uGc-xAm4dIWEVhIv/view?usp=drive_link",
    link: "/Halaman/page/2/2/11",
    category: "Crypto Trading Principle",
  },
];
