export const Data = [
  {
    id: "1",
    title: "Footprint Chart",
    drive: "https://youtu.be/T70bmDqNO3M?si=hNHYi0_zVttG94L3",
    link: "/Halaman/page/4/5/1",
    category: "How to Read Orderflow",
  },
  {
    id: "2",
    title: "Depth of Market",
    drive: "https://youtu.be/Qxx6AJ9BZu8?si=ZAEWehK44pBWAv1F",
    link: "/Halaman/page/4/5/2",
    category: "How to Read Orderflow",
  },
  {
    id: "3",
    title: "What is CVD",
    drive: "https://youtu.be/NDHbEYeDQhs?si=FHNBY3QvrAV9Dg-4",
    link: "/Halaman/page/4/5/3",
    category: "How to Read Orderflow",
  },
  {
    id: "4",
    title: "What is OI",
    drive: "https://youtu.be/1Nlov9V_KoE?si=mn69zKWXuNB_GnoK",
    link: "/Halaman/page/4/5/4",
    category: "How to Read Orderflow",
  },
  {
    id: "5",
    title: "What is Liquidations",
    drive: "https://youtu.be/vY_hVHLbsR4?si=IMAypaYIxvFllmrn",
    link: "/Halaman/page/4/5/5",
    category: "How to Read Orderflow",
  },
  {
    id: "6",
    title: "What is Funding Rates",
    drive: "https://youtu.be/Lp7hAbaM2Ws?si=D0fwEnMekOxT1NwM",
    link: "/Halaman/page/4/5/6",
    category: "How to Read Orderflow",
  },
  {
    id: "7",
    title: "How to Spot Absorption Using Footprint Charts",
    drive: "https://youtu.be/UV04Uzv_74w?si=JgR8I3QqY2l_bbI9",
    link: "/Halaman/page/4/5/7",
    category: "How to Read Orderflow",
  },
  {
    id: "8",
    title: "Positions Closing vs Postions Entering",
    drive: "https://youtu.be/6d9j1FnT8Kk?si=uBcyEoJJO29ykwZO",
    link: "/Halaman/page/4/5/8",
    category: "How to Read Orderflow",
  },
  {
    id: "9",
    title: "Order Block Explained",
    drive: "https://youtu.be/QZcanVTz_zs?si=LMQR2oMyYJapd2ya",
    link: "/Halaman/page/4/5/9",
    category: "How to Read Orderflow",
  },
  {
    id: "10",
    title: "Orderbook Depth",
    drive: "https://youtu.be/9FRSRrDMXMc?si=NRIlzSJxv6En25Ia",
    link: "/Halaman/page/4/5/10",
    category: "How to Read Orderflow",
  },
  {
    id: "11",
    title: "How to Use Relative Volume",
    drive: "https://youtu.be/7D3yECiakzo?si=dXs7ewfCfiIJqJ7h",
    link: "/Halaman/page/4/5/11",
    category: "How to Read Orderflow",
  },
];
