export const Data = [
  {
    id: "1",
    title: "Auction Market Theory",
    drive: "https://drive.google.com/file/d/19uMSLoNlLL8IsXYZ2BG1becwMaaZ0d6S/view?usp=drive_link",
    link: "/Halaman/page/4/1/1",
    category: "Auction Market Theory",
  },
  {
    id: "2",
    title: "Balance Market vs Imbalance Market",
    drive: "https://drive.google.com/file/d/1MptwaqRgTUJ5LbHuk81wtDPxefmhYM9j/view?usp=drive_link",
    link: "/Halaman/page/4/1/2",
    category: "Auction Market Theory",
  },
  {
    id: "3",
    title: "How to Define Range",
    drive: "https://drive.google.com/file/d/13i40F59Hfej6g7VEG68MFwPXBb4MV3Tx/view?usp=drive_link",
    link: "/Halaman/page/4/1/3",
    category: "Auction Market Theory",
  },
  {
    id: "4",
    title: "How to Use Market Profile (TPO Chart)",
    drive: "https://drive.google.com/file/d/1-ce2xFd5y_CHVN6nMV2kwzkqEe4u97jX/view?usp=drive_link",
    link: "/Halaman/page/4/1/4",
    category: "Auction Market Theory",
  },
  {
    id: "5",
    title: "How to Use Volume Profile",
    drive: "https://drive.google.com/file/d/1_39Z8qEchArRJra4lWx0BkLRx2iW8Iwu/view?usp=drive_link",
    link: "/Halaman/page/4/1/5",
    category: "Auction Market Theory",
  },
  {
    id: "6",
    title: "VWAP Explained",
    drive: "https://drive.google.com/file/d/1-LGlS2RU76rP752YBaOKIA-TuUV4NRGZ/view?usp=drive_link",
    link: "/Halaman/page/4/1/6",
    category: "Auction Market Theory",
  },
  {
    id: "7",
    title: "How to Define Range",
    drive: "https://drive.google.com/file/d/1BlTl2cWDe29iosl5gysvLgu5TPRDPbGp/view?usp=drive_link",
    link: "/Halaman/page/4/1/7",
    category: "Auction Market Theory",
  },
];
