export const tradingData = [
  {
    title: "Crypto Fundamentals Guide",
    image: "/images/A2.webp", 
    link: "/Halaman/page/1/2",
    category: "Modul Level 0",
  },
  {
    title: "Cara Memilih Exchange Crypto",
    image: "/images/A3.webp", 
    link: "/Halaman/page/1/3",
    category: "Modul Level 0",
  },
  {
    title: "Leverage 101",
    image: "/images/A4.webp", 
    link: "/Halaman/page/1/4",
    category: "Modul Level 0",
  },
  {
    title: "Cara Pakai Tradingview Dari 0",
    image: "/images/A5.webp", 
    link: "/Halaman/page/1/5",
    category: "Modul Level 0",
  },
  {
    title: "Crypto Judi Atau Investasi",
    image: "/images/A6.webp", 
    link: "/Halaman/page/1/6",
    category: "Modul Level 0",
  },
  {
    title: "Diversification",
    image: "/images/A7.webp", 
    link: "/Halaman/page/1/7",
    category: "Modul Level 0",
  },
  {
    title: "FAQ and Mind Management",
    image: "/images/A8.webp",
    link: "/Halaman/page/1/8",
    category: "Modul Level 0",
  },
  {
    title: "Order Type",
    image: "/images/A9.webp",
    link: "/Halaman/page/1/9",
    category: "Modul Level 0",
  },
  {
    title: "Intro to Web3 Jobs",
    image: "/images/A10.webp",
    link: "/Halaman/page/1/10",
    category: "Modul Level 0",
  },
    {
    title: "Zero To Hero Web3 Jobs",
    image: "/images/zero-to-hero.webp",
    link: "/Halaman/page/1/12",
    category: "Modul Level 0",
  },
    {
    title: "Basic Market",
    image: "/images/B1.webp", 
    link: "/Halaman/page/2/1",
    category: "Modul Level 1",
  },
  {
    title: "Crypto Trading Principle",
    image: "/images/B2.webp", 
    link: "/Halaman/page/2/2",
    category: "Modul Level 1",
  },
  {
    title: "Core Technical Analysis Logic",
    image: "/images/B3.webp", 
    link: "/Halaman/page/2/3",
    category: "Modul Level 1",
  },
  {
    title: "Crypto Trend Guide",
    image: "/images/B4.webp", 
    link: "/Halaman/page/2/4",
    category: "Modul Level 1",
  },
  {
    title: "Crypto Index Guide",
    image: "/images/B5.webp", 
    link: "/Halaman/page/2/5",
    category: "Modul Level 1",
  },
  {
    title: "Crypto Fibonacci Guide",
    image: "/images/B6.webp", 
    link: "/Halaman/page/2/6",
    category: "Modul Level 1",
  },
  {
    title: "Crypto On-Chain Transfer Guide",
    image: "/images/B7.webp", 
    link: "/Halaman/page/2/7",
    category: "Modul Level 1",
  },
  {
    title: "ear Market Strategy",
    image: "/images/B8.webp", 
    link: "/Halaman/page/2/8",
    category: "Modul Level 1",
  },
  {
    title: "Safety Series",
    image: "/images/B9.webp", 
    link: "/Halaman/page/2/9",
    category: "Modul Level 1",
  },
  {
    title: "Web3 Jobs Series: Experienced Interview",
    image: "/images/B10.webp", 
    link: "/Halaman/page/2/10",
    category: "Modul Level 1",
  },
  {
    title: "Money Management on Perp Trading",
    image: "/images/B11.webp", 
    link: "/Halaman/page/2/11",
    category: "Modul Level 1",
  },
  {
    title: "Bahas Geopolitik: Iran vs Israel",
    image: "/images/B12.webp", 
    link: "/Halaman/page/2/12",
    category: "Modul Level 1",
  },
  {
    title: "Probability Game",
    image: "/images/B13.webp", 
    link: "/Halaman/page/2/13",
    category: "Modul Level 1",
  },
  {
    title: "rading Korelasi DCA etc",
    image: "/images/B14.webp", 
    link: "/Halaman/page/2/14",
    category: "Modul Level 1",
  },
  {
    title: "Apakah Bisa Bebas Finansial Lewat Crypto?",
    image: "/images/B15.webp", 
    link: "/Halaman/page/2/15",
    category: "Modul Level 1",
  },
  {
    title: "bias-didunia-investasi",
    image: "/images/bias-didunia-investasi.webp", 
    link: "/Halaman/page/2/17",
    category: "Modul Level 1",
  },
  {
    title: "qunat-performing",
    image: "/images/qunat-performing.webp", 
    link: "/Halaman/page/2/18",
    category: "Modul Level 1",
  },
  {
    title: "tws-internal",
    image: "/images/tws-internal.webp", 
    link: "/Halaman/page/2/19",
    category: "Modul Level 1",
  },
  {
    title: "-",
    image: "/images/-.webp", 
    link: "/Halaman/page/2/20",
    category: "Modul Level 1",
  },
  {
    title: "meme-coin",
    image: "/images/meme-coin.webp", 
    link: "/Halaman/page/2/21",
    category: "Modul Level 1",
  },
  {
    title: "crypto-candel",
    image: "/images/crypto-candel.webp", 
    link: "/Halaman/page/2/22",
    category: "Modul Level 1",
  },
  {
    title: "-",
    image: "/images/-.webp", 
    link: "/Halaman/page/2/23",
    category: "Modul Level 1",
  },
  {
    title: "trend-following",
    image: "/images/trend-following.webp", 
    link: "/Halaman/page/2/24",
    category: "Modul Level 1",
  },
    {
    title: "Suli 2024 Liveclass Archive",
    image: "/images/C1.webp", 
    link: "/Halaman/page/3/1",
    category: "Modul Level 3",
  },
  {
    title: "-",
    image: "/images/C2.webp", 
    link: "/Halaman/page/3/2",
    category: "Modul Level 3",
  },
  {
    title: "-",
    image: "/images/C3.webp", 
    link: "/Halaman/page/3/3",
    category: "Modul Level 3",
  },
  {
    title: "-",
    image: "/images/C4.webp", 
    link: "/Halaman/page/3/4",
    category: "Modul Level 3",
  },
  {
    title: "-",
    image: "/images/C5.webp", 
    link: "/Halaman/page/3/5",
    category: "Modul Level 3",
  },
  {
    title: "-",
    image: "/images/C6.webp", 
    link: "/Halaman/page/3/6",
    category: "Modul Level 3",
  },
  {
    title: "Live Suli",
    image: "/images/livesuli.webp", 
    link: "/Halaman/page/3/7",
    category: "Modul Level 3",
  },
  {
    title: "-",
    image: "/images/trand-bassic.webp", 
    link: "/Halaman/page/3/8",
    category: "Modul Level 3",
  },
  {
    title: "-",
    image: "/images/cara-set-kriteria-trading.webp", 
    link: "/Halaman/page/3/9",
    category: "Modul Level 3",
  },
  {
    title: "Live Quant",
    image: "/images/livequant.webp", 
    link: "/Halaman/page/3/10",
    category: "Modul Level 3",
  },
  {
    title: "Live Mira",
    image: "/images/livemira.webp", 
    link: "/Halaman/page/3/11",
    category: "Modul Level 3",
  },
    {
    title: "-",
    image: "/images/D2.webp", 
    link: "/Halaman/page/4/1",
    category: "Modul Level 4",
  },
  {
    title: "-",
    image: "/images/D3.webp", 
    link: "/Halaman/page/4/2",
    category: "Modul Level 4",
  },
  {
    title: "-",
    image: "/images/D4.webp", 
    link: "/Halaman/page/4/3",
    category: "Modul Level 4",
  },
  {
    title: "-",
    image: "/images/D5.webp", 
    link: "/Halaman/page/4/4",
    category: "Modul Level 4",
  },
  {
    title: "-",
    image: "/images/D6.webp", 
    link: "/Halaman/page/4/5",
    category: "Modul Level 4",
  },
  {
    title: "-",
    image: "/images/D1.webp", 
    link: "/Halaman/page/4/6",
    category: "Modul Level 4",
  },
  {
    title: "Trend Following Advanced: Timing Altcoin Season",
    image: "/images/-.webp", 
    link: "/Halaman/page/4/7",
    category: "Modul Level 4",
  },
  {
    title: "-",
    image: "/images/exsecutiuon.webp", 
    link: "/Halaman/page/4/8",
    category: "Modul Level 4",
  },
  {
    title: "Trend Following Advanced: Timing The Crypto Cycle",
    image: "/images/-.webp", 
    link: "/Halaman/page/4/9",
    category: "Modul Level 4",
  },
];