export const Data = [
  {
    id: "1",
    title: "Crypto Capital Preservation",
    drive: "https://youtu.be/nKJ2j4TswEU?si=fd88HHf-5z_NnWg0",
    link: "/Halaman/page/2/2/1",
    category: "Crypto Trading Principle",
  },
  {
    id: "2",
    title: "Hindari Terkena Drawdown Portfolio dalam",
    drive: "https://youtu.be/BAFO31AauK8?si=erit5GEoV5D9e67O",
    link: "/Halaman/page/2/2/2",
    category: "Crypto Trading Principle",
  },
  {
    id: "3",
    title: "Jangan Perna Trading Tanpa Stoploss",
    drive: "https://youtu.be/CzJG8kZRLa8?si=l6261C9zVtwenSWc",
    link: "/Halaman/page/2/2/3",
    category: "Crypto Trading Principle",
  },
  {
    id: "4",
    title: "If It's Too Good To Be True, Then It Is To Good To Be True",
    drive: "https://youtu.be/JitNNRW9KXI?si=wUyvD3NMLf-GQLxu",
    link: "/Halaman/page/2/2/4",
    category: "Crypto Trading Principle",
  },
  {
    id: "5",
    title: "Cara Main Setiap Market Beda",
    drive: "https://youtu.be/c7ir4Y8TFwU?si=z_4PIn7EFCcXJXta",
    link: "/Halaman/page/2/2/5",
    category: "Crypto Trading Principle",
  },
  {
    id: "6",
    title: "Seacrh For Market Confluence",
    drive: "https://youtu.be/onZ-UNeKN9M?si=ur95yXEGRtr_4nur",
    link: "/Halaman/page/2/2/6",
    category: "Crypto Trading Principle",
  },
  {
    id: "7",
    title: "Jangan Batesin Profit, Tapi Batesin Loss",
    drive: "https://youtu.be/KvOac9o51lE?si=GF4ZqcJsFyiBy9iP",
    link: "/Halaman/page/2/2/7",
    category: "Crypto Trading Principle",
  },
  {
    id: "8",
    title: "Anaylst Terbaik Adalah Diri Kalian Sendiri",
    drive: "https://youtu.be/h-zhFOqq3uM?si=YMSXrVh3SNv3cb-u",
    link: "/Halaman/page/2/2/8",
    category: "Crypto Trading Principle",
  },
  {
    id: "9",
    title: "Exit Strategy 90% Dari Total Trade Kalian",
    drive: "https://youtu.be/Vz5ptEziwDU?si=XyiqTfPH4Wjfd8tM",
    link: "/Halaman/page/2/2/9",
    category: "Crypto Trading Principle",
  },
  {
    id: "10",
    title: "Trade Less When Winning",
    drive: "https://youtu.be/w8hoL9lrISc?si=sEr0IaiULZTRbheC",
    link: "/Halaman/page/2/2/10",
    category: "Crypto Trading Principle",
  },
  {
    id: "11",
    title: "Selama ini Lu Salah Pake Trading Journal",
    drive: "https://youtu.be/0Fa8_XRge_Q?si=o8k89Tug08Y8547s",
    link: "/Halaman/page/2/2/11",
    category: "Crypto Trading Principle",
  },
];
