export const Data = [
  {
    id: "1",
    title: "Footprint Chart",
    drive: "https://drive.google.com/file/d/1yOe9wm404EhWWxzE8M3NpiNVcmNzG5ed/view?usp=drive_link",
    link: "/Halaman/page/4/5/1",
    category: "How to Read Orderflow",
  },
  {
    id: "2",
    title: "Depth of Market",
    drive: "https://drive.google.com/file/d/10hfbkrZ3RSr51QKtApESUMl_8Is0h0wn/view?usp=drive_link",
    link: "/Halaman/page/4/5/2",
    category: "How to Read Orderflow",
  },
  {
    id: "3",
    title: "What is CVD",
    drive: "https://drive.google.com/file/d/1Wx7ltwDOZ-js8Ff2MrnQGfvlp-26uLq2/view?usp=drive_link",
    link: "/Halaman/page/4/5/3",
    category: "How to Read Orderflow",
  },
  {
    id: "4",
    title: "What is OI",
    drive: "https://drive.google.com/file/d/1RarTAHr8_mg29Et2qhJvpwRqrC48d6w5/view?usp=drive_link",
    link: "/Halaman/page/4/5/4",
    category: "How to Read Orderflow",
  },
  {
    id: "5",
    title: "What is Liquidations",
    drive: "https://drive.google.com/file/d/1XjtA80W1QMOmevLikieX96tLIhEafWPs/view?usp=drive_link",
    link: "/Halaman/page/4/5/5",
    category: "How to Read Orderflow",
  },
  {
    id: "6",
    title: "What is Funding Rates",
    drive: "https://drive.google.com/file/d/1NnqX0fOPWIPWLd11_yV4ZxHWiAT2QUvW/view?usp=drive_link",
    link: "/Halaman/page/4/5/6",
    category: "How to Read Orderflow",
  },
  {
    id: "7",
    title: "How to Spot Absorption Using Footprint Charts",
    drive: "https://drive.google.com/file/d/1UZ_wbDoaEEbDO8_rvAUM2btcjkbJevli/view?usp=drive_link",
    link: "/Halaman/page/4/5/7",
    category: "How to Read Orderflow",
  },
  {
    id: "8",
    title: "Positions Closing vs Postions Entering",
    drive: "https://drive.google.com/file/d/1Q-QoLJLHKN-YZCnlkWKgvGfv8eQaB5GW/view?usp=drive_link",
    link: "/Halaman/page/4/5/8",
    category: "How to Read Orderflow",
  },
  {
    id: "9",
    title: "Order Block Explained",
    drive: "https://drive.google.com/file/d/19aSe-zUB0UkUAs8WhzRlebDZYiQtIhEc/view?usp=drive_link",
    link: "/Halaman/page/4/5/9",
    category: "How to Read Orderflow",
  },
  {
    id: "10",
    title: "Orderbook Depth",
    drive: "https://drive.google.com/file/d/1VtMzlFWX41qIy6MJRiS0xLHQ_R5OtS2R/view?usp=drive_link",
    link: "/Halaman/page/4/5/10",
    category: "How to Read Orderflow",
  },
  {
    id: "11",
    title: "How to Use Relative Volume",
    drive: "https://drive.google.com/file/d/1n054XsYoaU-6reUK9bR-wpwnE5tLr7El/view?usp=drive_link",
    link: "/Halaman/page/4/5/11",
    category: "How to Read Orderflow",
  },
];
