export const Data = [
  {
    id: "1",
    title: "Member Only Live Replay Sulianto & Quant, 5 Juni 2025",
    drive: "https://drive.google.com/file/d/1H6l8gfFO3j2-5gvq2n-LcqvccDNjVolX/view?usp=drive_link",
    link: "/Halaman/page/3/7/1",
    category: "Member Only Live Replay",
  },
  {
    id: "2",
    title: "Member Only Live Replay Sulianto, 26 Juni 2025",
    drive: "https://drive.google.com/file/d/1RB8LeSCdQPXQwIpE2cTOC3XCcJnqzR3u/view?usp=drive_link",
    link: "/Halaman/page/3/7/2",
    category: "Member Only Live Replay",
  },
  {
    id: "3",
    title: "Member Only Live Replay Quant, 18 Juni 2025",
    drive: "https://drive.google.com/file/d/11H2F8coz-w3oH4VF5u7jiKNrCAZFrFDn/view?usp=drive_link",
    link: "/Halaman/page/3/7/3",
    category: "Member Only Live Replay",
  },
  {
    id: "5",
    title: "Member Only Live Replay Quant, 23 Juni 2025",
    drive: "https://drive.google.com/file/d/1Cu1ybV14CCiEY6kmeHjFqfkNQ4RXIItV/view?usp=drive_link",
    link: "/Halaman/page/3/7/5",
    category: "Member Only Live Replay",
  },
  {
    id: "6",
    title: "Member Only Live Replay Quant, 25 Juni 2025",
    drive: "https://drive.google.com/file/d/1gHF05hYDdCHNqnrIPinOke2UUAx99yZb/view?usp=drive_link",
    link: "/Halaman/page/3/7/6",
    category: "Member Only Live Replay",
  },
  {
    id: "7",
    title: "Live Mira 28 Juni - Weekly Plan",
    drive: "https://drive.google.com/file/d/1fz-FkrGeSgcm_PKVcFt7Capmk0PAyyez/view?usp=drive_link",
    link: "/Halaman/page/3/7/7",
    category: "Member Only Live Replay",
  },
  {
    id: "8",
    title: "Mira Live Answer Your Question",
    drive: "https://drive.google.com/file/d/1KjnBR5kliti6t3Nr-su308yJcQKC_hWT/view?usp=drive_link",
    link: "/Halaman/page/3/7/8",
    category: "Member Only Live Replay",
  },
];
