export const Data = [
  {
    id: "1",
    title: "Member Only Live Replay Sulianto & Quant, 5 Juni 2025",
    drive: "https://youtu.be/RLvC8K-qTeI?si=VZZx89aqRFQNB-IV",
    link: "/Halaman/page/3/7/1",
    category: "Member Only Live Replay",
  },
  {
    id: "2",
    title: "Member Only Live Replay Sulianto, 26 Juni 2025",
    drive: "https://youtu.be/McnmEIY-jWk?si=4Nk5W75ysbHEeEbs",
    link: "/Halaman/page/3/7/2",
    category: "Member Only Live Replay",
  },
  {
    id: "3",
    title: "Member Only Live Replay Quant, 18 Juni 2025",
    drive: "https://youtu.be/eIUyel7ymEY?si=wSqdQpmnxqL6ZvF5",
    link: "/Halaman/page/3/7/3",
    category: "Member Only Live Replay",
  },
  {
    id: "4",
    title: "Member Only Live Replay Quant, 23 Juni 2025",
    drive: "https://youtu.be/y8hNP_qEbNc?si=OuOCNoWz6w7Id2qU",
    link: "/Halaman/page/3/7/4",
    category: "Member Only Live Replay",
  },
  {
    id: "5",
    title: "Member Only Live Replay Quant, 25 Juni 2025",
    drive: "https://youtu.be/GD7kSeNFyYE?si=gEelOD0b8psGkEuX",
    link: "/Halaman/page/3/7/5",
    category: "Member Only Live Replay",
  },
  {
    id: "6",
    title: "Live Mira 28 Juni - Weekly Plan",
    drive: "https://youtu.be/rUJT7ZDEjRw?si=-lakgdPMATdg4Ed8",
    link: "/Halaman/page/3/7/6",
    category: "Member Only Live Replay",
  },
  {
    id: "7",
    title: "Mira Live Answer Your Question",
    drive: "https://youtu.be/n6V6wxjCPZI?si=YbcZD6RcEFiw5rsg",
    link: "/Halaman/page/3/7/7",
    category: "Member Only Live Replay",
  },
  {
    id: "8",
    title: "Mira Live 30 Juni - Daily Plan",
    drive: "https://youtu.be/2dYGO4PBcZY?si=ktGrP-QOheVzLkjg",
    link: "/Halaman/page/3/7/8",
    category: "Member Only Live Replay",
  },
  {
    id: "9",
    title: "Mira Live 2 Juli - Daily Plan",
    drive: "https://youtu.be/BowED-uDyKY?si=hD2mDsvlOVYTptr9",
    link: "/Halaman/page/3/7/9",
    category: "Member Only Live Replay",
  },
  {
    id: "10",
    title: "Mira Live 5 Juli - Weekly Plan",
    drive: "https://youtu.be/Lg11bPt_v_A?si=eirjQrgGabRldniO",
    link: "/Halaman/page/3/7/10",
    category: "Member Only Live Replay",
  },
  {
    id: "11",
    title: "Mira Live 7 Juli - Daily Plan",
    drive: "https://youtu.be/pY07G3gqO9o?si=gwRYhPrSgGlrBa4M",
    link: "/Halaman/page/3/7/11",
    category: "Member Only Live Replay",
  },
  {
    id: "12",
    title: "Mira Live 10 Juli - Daily Plan",
    drive: "https://youtu.be/n8WxW0hekAI?si=VqHNoSxWbNMC5JyE",
    link: "/Halaman/page/3/7/12",
    category: "Member Only Live Replay",
  },
  {
    id: "13",
    title: "Quant Live 11 Juli 2025 - Bitcoin ATH Market Update",
    drive: "https://youtu.be/Qi_5jrJlwX8?si=IrU7HgliBRdi23FA",
    link: "/Halaman/page/3/7/13",
    category: "Member Only Live Replay",
  },
  {
    id: "14",
    title: "Mira Live 12 Juli - Screening",
    drive: "https://youtu.be/p9DwTQozfG4?si=X-dbeqzVm4JKJ2pV",
    link: "/Halaman/page/3/7/14",
    category: "Member Only Live Replay",
  },
  {
    id: "15",
    title: "Quant Live 13 Juli 2025 - Bitcoin ATH Market Update  ",
    drive: "https://youtu.be/wbnCPbmx5Do?si=uYTGHDHz0kIjjfHO",
    link: "/Halaman/page/3/7/15",
    category: "Member Only Live Replay",
  },
  {
    id: "16",
    title: "Mira Live 14 Juli - Screening",
    drive: "https://youtu.be/zPqTGllyxWo?si=5oFvefWg5mZxU15Z",
    link: "/Halaman/page/3/7/16",
    category: "Member Only Live Replay",
  },
  {
    id: "17",
    title: "Quant Live 15 Juli 2025 ",
    drive: "https://youtu.be/ktJvkZVyXwE?si=xmaVmY7iuL_TCsKV",
    link: "/Halaman/page/3/7/17",
    category: "Member Only Live Replay",
  },
  {
    id: "18",
    title: "Quant Live 16 Juli 2025",
    drive: "https://youtu.be/d3bXvFCkMl0?si=IeEKIpJV_oGmjcvQ",
    link: "/Halaman/page/3/7/18",
    category: "Member Only Live Replay",
  },
  {
    id: "19",
    title: "Mira Live 17 Juli - Screening",
    drive: "https://youtu.be/6e1HvS5FT6s?si=bXbduxmeC1m4p59V",
    link: "/Halaman/page/3/7/19",
    category: "Member Only Live Replay",
  },
  {
    id: "20",
    title: "Quant Live 19 Juli 2025",
    drive: "https://youtu.be/W9pUM5xhiSA?si=F8lVZqCothSe6kqW",
    link: "/Halaman/page/3/7/20",
    category: "Member Only Live Replay",
  },
  {
    id: "21",
    title: "Mira Live 20 Juli - Weekly Plan",
    drive: "https://youtu.be/BxaIsLhIGAo?si=ztbCFjO2-cfko-ux",
    link: "/Halaman/page/3/7/21",
    category: "Member Only Live Replay",
  },
  {
    id: "22",
    title: "Mira Live 21 Juli - Daily Plan",
    drive: "https://youtu.be/hFlkiTL4sao?si=EW-KTqYLVe6hd0jY",
    link: "/Halaman/page/3/7/22",
    category: "Member Only Live Replay",
  },
];
