export const tradingData = [
  {
    title: "On Boarding Premium Membership",
    image: "/images/A1.webp", 
    link: "/Halaman/page/1/1",
    category: "Modul Level 0",
  },
  {
    title: "Bias Didunia Investasi",
    image: "/images/bias-didunia-investasi.webp", 
    link: "/Halaman/page/2/17",
    category: "Modul Level 0",
  },
  {
    title: "Cara Set Kriteria Trading",
    image: "/images/cara-set-kriteria-trading.webp", 
    link: "/Halaman/page/3/9",
    category: "Modul Level 1",
  },
  {
    title: "Zero To Hero",
    image: "/images/zero-to-hero.webp", 
    link: "/Halaman/page/1/12",
    category: "Modul Level 0",
  },
  {
    title: "Crypto Fundamentals Guide",
    image: "/images/A2.webp", 
    link: "/Halaman/page/1/2",
    category: "Modul Level 0",
  },
  {
    title: "Cara Pakai Tradingview Dari 0",
    image: "/images/A5.webp", 
    link: "/Halaman/page/1/5",
    category: "Modul Level 0",
  },
  {
    title: "FAQ and Mind Management",
    image: "/images/A8.webp",
    link: "/Halaman/page/1/8",
    category: "Modul Level 0",
  },
  {
    title: "Order Type",
    image: "/images/A9.webp",
    link: "/Halaman/page/1/9",
    category: "Modul Level 0",
  },
  {
    title: "Intro to Web3 Jobs",
    image: "/images/A10.webp",
    link: "/Halaman/page/1/10",
    category: "Modul Level 0",
  },
  {
    title: "-",
    image: "/images/B2.webp", 
    link: "/Halaman/page/2/2",
    category: "Modul Level 1",
  },
  {
    title: "-",
    image: "/images/B3.webp", 
    link: "/Halaman/page/2/3",
    category: "Modul Level 1",
  },
  {
    title: "-",
    image: "/images/B4.webp", 
    link: "/Halaman/page/2/4",
    category: "Modul Level 1",
  },
  {
    title: "-",
    image: "/images/B5.webp", 
    link: "/Halaman/page/2/5",
    category: "Modul Level 1",
  },
  {
    title: "-",
    image: "/images/B6.webp", 
    link: "/Halaman/page/2/6",
    category: "Modul Level 1",
  },
  {
    title: "-",
    image: "/images/B8.webp", 
    link: "/Halaman/page/2/8",
    category: "Modul Level 1",
  },
  {
    title: "-",
    image: "/images/B10.webp", 
    link: "/Halaman/page/2/10",
    category: "Modul Level 1",
  },
  {
    title: "-",
    image: "/images/B13.webp", 
    link: "/Halaman/page/2/13",
    category: "Modul Level 1",
  },
  {
    title: "-",
    image: "/images/B15.webp", 
    link: "/Halaman/page/2/15",
    category: "Modul Level 1",
  },
  {
    title: "-",
    image: "/images/C1.webp", 
    link: "/Halaman/page/3/1",
    category: "Modul Level 2",
  },
  {
    title: "-",
    image: "/images/C3.webp", 
    link: "/Halaman/page/3/3",
    category: "Modul Level 2",
  },
  {
    title: "-",
    image: "/images/C5.webp", 
    link: "/Halaman/page/3/5",
    category: "Modul Level 2",
  },
  {
    title: "-",
    image: "/images/C7.webp", 
    link: "/Halaman/page/3/7",
    category: "Modul Level 2",
  },
  {
    title: "Leverage 101",
    image: "/images/A4.webp", 
    link: "/Halaman/page/1/4",
    category: "Modul Level 0",
  },
];
