export const Data = [
  {
    id: "1",
    title: "Live Mira 28 Juni - Weekly Plan",
    drive: "https://youtu.be/rUJT7ZDEjRw?si=-lakgdPMATdg4Ed8",
    link: "/Halaman/page/3/11/1",
    category: "Member Only Live Replay",
  },
  {
    id: "2",
    title: "Mira Live Answer Your Question",
    drive: "https://youtu.be/n6V6wxjCPZI?si=YbcZD6RcEFiw5rsg",
    link: "/Halaman/page/3/11/2",
    category: "Member Only Live Replay",
  },
  {
    id: "3",
    title: "Mira Live 30 Juni - Daily Plan",
    drive: "https://youtu.be/2dYGO4PBcZY?si=ktGrP-QOheVzLkjg",
    link: "/Halaman/page/3/11/3",
    category: "Member Only Live Replay",
  },
  {
    id: "4",
    title: "Mira Live 2 Juli - Daily Plan",
    drive: "https://youtu.be/BowED-uDyKY?si=hD2mDsvlOVYTptr9",
    link: "/Halaman/page/3/11/4",
    category: "Member Only Live Replay",
  },
  {
    id: "5",
    title: "Mira Live 5 Juli - Weekly Plan",
    drive: "https://youtu.be/Lg11bPt_v_A?si=eirjQrgGabRldniO",
    link: "/Halaman/page/3/11/5",
    category: "Member Only Live Replay",
  },
  {
    id: "6",
    title: "Mira Live 7 Juli - Daily Plan",
    drive: "https://youtu.be/pY07G3gqO9o?si=gwRYhPrSgGlrBa4M",
    link: "/Halaman/page/3/11/6",
    category: "Member Only Live Replay",
  },
  {
    id: "7",
    title: "Mira Live 10 Juli - Daily Plan",
    drive: "https://youtu.be/n8WxW0hekAI?si=VqHNoSxWbNMC5JyE",
    link: "/Halaman/page/3/11/7",
    category: "Member Only Live Replay",
  },
  {
    id: "8",
    title: "Mira Live 12 Juli - Screening",
    drive: "https://youtu.be/p9DwTQozfG4?si=X-dbeqzVm4JKJ2pV",
    link: "/Halaman/page/3/11/8",
    category: "Member Only Live Replay",
  },
  {
    id: "9",
    title: "Mira Live 14 Juli - Screening",
    drive: "https://youtu.be/zPqTGllyxWo?si=5oFvefWg5mZxU15Z",
    link: "/Halaman/page/3/11/9",
    category: "Member Only Live Replay",
  },
  {
    id: "10",
    title: "Mira Live 17 Juli - Screening",
    drive: "https://youtu.be/6e1HvS5FT6s?si=bXbduxmeC1m4p59V",
    link: "/Halaman/page/3/11/10",
    category: "Member Only Live Replay",
  },
  {
    id: "11",
    title: "Mira Live 20 Juli - Weekly Plan",
    drive: "https://youtu.be/BxaIsLhIGAo?si=ztbCFjO2-cfko-ux",
    link: "/Halaman/page/3/11/11",
    category: "Member Only Live Replay",
  },
  {
    id: "12",
    title: "Mira Live 21 Juli - Daily Plan",
    drive: "https://youtu.be/hFlkiTL4sao?si=EW-KTqYLVe6hd0jY",
    link: "/Halaman/page/3/10/12",
    category: "Member Only Live Replay",
  },
  {
    id: "13",
    title: "Mira Live 24 Juli - Weekly Plan",
    drive: "https://youtu.be/GU8dakyFLWo",
    link: "/Halaman/page/3/11/13",
    category: "Member Only Live Replay",
  },
  {
    id: "14",
    title: "Mira Live 26 Juli - Daily Plan",
    drive: "https://youtu.be/WUVM8QNs40U",
    link: "/Halaman/page/3/10/14",
    category: "Member Only Live Replay",
  },
];
