export const Data = [
  {
    id: "1",
    title: "Liquidity Sweep Anlaysis",
    drive: "https://drive.google.com/file/d/1wHjVZboGAo9UzR6j3urP0ztDSUoXgjzM/view?usp=drive_link",
    link: "/Halaman/page/3/1/1",
    category: "Suli 2024 Liveclass Archive",
  },
  {
    id: "2",
    title: "Market Gap Analysis",
    drive: "https://drive.google.com/file/d/1XzzlH__Lnj5zMvRXSctCl2cXwYsuSlw4/view?usp=drive_link",
    link: "/Halaman/page/3//2",
    category: "Suli 2024 Liveclass Archive",
  },
  {
    id: "3",
    title: "Candlestick Pattern Analysis",
    drive: "https://drive.google.com/file/d/11DgfgNDQuxzWeCgNp8y4OhwoyZGqePXI/view?usp=drive_link",
    link: "/Halaman/page/3/1/3",
    category: "Suli 2024 Liveclass Archive",
  },
  {
    id: "4",
    title: "Trendline Breakout Analysis",
    drive: "https://drive.google.com/file/d/1dmxjLICCgFsQY4Jy1Jm8jVlFw7rGdEvE/view?usp=drive_link",
    link: "/Halaman/page/3/1/4",
    category: "Suli 2024 Liveclass Archive",
  },
  {
    id: "5",
    title: "Advanced Fibonacci Analysis",
    drive: "https://drive.google.com/file/d/1zIMvxs78_OkZt9PcprAs0ieF7kHM7kIY/view?usp=drive_link",
    link: "/Halaman/page/3/1/5",
    category: "Suli 2024 Liveclass Archive",
  },
  {
    id: "6",
    title: "Chart Pattern Analysis",
    drive: "https://drive.google.com/file/d/1jcmPKBeqoUE8LIpw6w5oDYqHLsJ10yQT/view?usp=drive_link",
    link: "/Halaman/page/3/1/6",
    category: "Suli 2024 Liveclass Archive",
  },
  {
    id: "7",
    title: "Market Volume Analysis",
    drive: "https://drive.google.com/file/d/1tAsn8M5IbcyYV6WP7xJp5qKmGgkz-HiV/view?usp=drive_link",
    link: "/Halaman/page/3/1/7",
    category: "Suli 2024 Liveclass Archive",
  },
  {
    id: "8",
    title: "Orderblock",
    drive: "https://drive.google.com/file/d/1pJ86IUS3GFRoBzrQO4ZJtSABAB4drRJ7/view?usp=drive_link",
    link: "/Halaman/page/3/1/8",
    category: "Suli 2024 Liveclass Archive",
  },
];
