export const Data = [
  {
    id: "1",
    title: "Liquidity Sweep Anlaysis",
    drive: "https://youtu.be/YOrn2qMF9Mc?si=RDgu4K7FIVFaz8md",
    link: "/Halaman/page/3/1/1",
    category: "Suli 2024 Liveclass Archive",
  },
  {
    id: "2",
    title: "Market Gap Analysis",
    drive: "https://youtu.be/KPpaJjgMq9g?si=u9tu9dCe0dtvja2Y",
    link: "/Halaman/page/3//2",
    category: "Suli 2024 Liveclass Archive",
  },
  {
    id: "3",
    title: "Candlestick Pattern Analysis",
    drive: "https://youtu.be/JUxzoV0vtkE?si=_PX4cBNQMzts8o3U",
    link: "/Halaman/page/3/1/3",
    category: "Suli 2024 Liveclass Archive",
  },
  {
    id: "4",
    title: "Trendline Breakout Analysis",
    drive: "https://youtu.be/ouQaDvnbuJE?si=l3D_t0atlqVibV1P",
    link: "/Halaman/page/3/1/4",
    category: "Suli 2024 Liveclass Archive",
  },
  {
    id: "5",
    title: "Advanced Fibonacci Analysis",
    drive: "https://youtu.be/D3iTcqshvyQ?si=8dOI8W0vLfZURipl",
    link: "/Halaman/page/3/1/5",
    category: "Suli 2024 Liveclass Archive",
  },
  {
    id: "6",
    title: "Chart Pattern Analysis",
    drive: "https://youtu.be/7Mx_VW5u1sM?si=UjkYc-LgXMrrPer8",
    link: "/Halaman/page/3/1/6",
    category: "Suli 2024 Liveclass Archive",
  },
  {
    id: "7",
    title: "Market Volume Analysis",
    drive: "https://youtu.be/jUfa4BeAyjY?si=VPIwEmuz1Y3U-pZ0",
    link: "/Halaman/page/3/1/7",
    category: "Suli 2024 Liveclass Archive",
  },
  {
    id: "8",
    title: "Orderblock",
    drive: "https://youtu.be/Poq-ZOCexNc?si=75SVgduG1iAjZMTN",
    link: "/Halaman/page/3/1/8",
    category: "Suli 2024 Liveclass Archive",
  },
];
